### ISSUE TITLE
No way to switch to frame parent

### ISSUE THREAD

**Issue by pwaller** [sourcegraph/go-selenium#12]
I've done `SwitchFrame()` to switch into an iframe and perform some actions, but then I need to switch out of it again and do something from outside that frame.

The wisdom on the internet seems to be that I either need to pass an integer "0" to switch to the frame with the first index, or call [`/session/{id}/frame/parent`](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidframe), neither of which seem possible in `go-selenium`. Would a pull request be accepted which adds `SwitchFrameParent()`?

**Comment by sqs** [comment]
Yes, absolutely! Thanks :)
