### ISSUE TITLE
Explicitly waiting for new page to load after Click()

### ISSUE THREAD

**Issue by chrissnell** [sourcegraph/go-selenium#30]
I'm writing a simple page performance tester.  I'm trying to fill in a form, issue a `Click()` on the submit button, and then gather timing information on the page that's returned by the server after the submission.  

I'm able to fill the form out (`FindElement()`, `SendKeys()`) and I can issue the `Click()` but I haven't figured out how to wait until the resulting new page is rendered before attempting to gather timings.  Is this possible in `go-selenium`?

**Comment by sqs** [comment]
I think you'll need to poll the page to see if the relevant elements are loaded. There is no clear definition of "loaded" as async JS might still be running and making network requests, so just poll for the element that you expect to see on the page.

**Comment by chrissnell** [comment]
OK, thanks!
