### ISSUE TITLE
How to set proxy?

### ISSUE THREAD

**Issue by guotie** [sourcegraph/go-selenium#33]
How to set proxy?

**Comment by sqs** [comment]
It uses a mostly default HTTP client (see https://sourcegraph.com/github.com/sourcegraph/go-selenium/-/blob/remote.go#L188:5). This means it uses [`http.DefaultTransport`](https://sourcegraph.com/github.com/golang/go@go1.7.1/-/blob/src/net/http/transport.go#L39:1). You can set the `HTTP_PROXY` or `HTTPS_PROXY` env vars, and they should take effect.

Please reopen if not so.
