### ISSUE TITLE
Element Screenshot

### ISSUE THREAD

**Issue by guotie** [sourcegraph/go-selenium#34]
webdriver has define element screenshot, in 18.2:  https://www.w3.org/TR/webdriver/#take-element-screenshot

I have try as this:

    func (elem *remoteWE) ScreenshotElement() ([]byte, error) {
	data, err := elem.parent.stringCommand("/session/%s/element/" + elem.id + "/screenshot")
	if err != nil {
		return nil, err
	}

	return []byte(data), nil
    }

But i cannot work, error is 404 Not found, why?

**Comment by sqs** [comment]
Which webdriver version and browser (chrome, FF, etc.) are you using?

**Comment by guotie** [comment]
chrome, 2.25

**Comment by sqs** [comment]
And you can confirm that version supports element screenshots? Can you cURL it or make it work with some other Selenium library?

**Comment by guotie** [comment]
I don't know whether it supports element screenshots. 

I find the webdrive defined this protocol, but i did not see some example which use this api to obtain element screenshot.

Most examples is:
1 screenshot the page;
2 obtain the element's location & size;
3 crop the page screenshot in the element position.
